version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=rootroot
      - DB_NAME=eLibrary
    depends_on:
      - database
    command: ./main

  database:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: eLibrary
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: